name: test-python
on: [push]
jobs:
  test-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install python
        with:
          python-version: 3.9

      - name: install dependencies
      - uses: actions/checkout@v1
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: test print
      - uses: actions/checkout@v1
        run: python python/python-test1.py
